<?php
if (basename($_SERVER['PHP_SELF']) == basename(__FILE__)) { 
	http_response_code(404);
	exit();
}

// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
// !!  I M P O R T A N T !                                                      !!
// !!  DO NOT EDIT THIS FILE! IT WILL BE OVERWRITTEN BY THE NEXT UPDATE!        !!
// !!  Use the config.php file instead!                                         !! 
// !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

// ###############################################################################
// SYSTEM SETTINGS
// ###############################################################################

	// In Maintenance Mode: Non-admin users cannot access the application	
	$maintenance_mode = false;	

	// Secure code extension active: Saves from manipulation of the code
	// Possible values:
	//    "none"  = no check
	//    "all"   = all checks
	//    "bin"   = only bin dir (login code)
	//    "cloud" = only cloud dir (application code)
	$SecureCode = 'all';
	
// ###############################################################################
// HOME NAS SETTINGS
// ###############################################################################
	$home_NAS_network   = false;  // Set to true to enable home NAS
	$home_NAS_autologin = false;  // Set to true to enable home NAS autologin (takes the first user account in the users.php file)
	
	
// ===============================================================================
// PATHS & FILES
// ===============================================================================

//  Default Directories
	// Parent directory of the current
	$work_dir              = dirname(__DIR__);
 	
 	// These are rarely used for cloud
 	$action_dir            = $work_dir . '/actions/';
 	$list_dir              = $work_dir . '/lists/';
 	
 	// The physical directory in which the cloud PHP files are stored
 	$cloud_dir             = $work_dir . '/cloud/';

    // The directory for temporary files (having those on the same partition dramatically speeds up the cloud)
 	$temp_dir              = $work_dir . '/tmp/';
 	
 	// The log file and path
	$log_file              = $list_dir . 'cloud.log';

    //  User database (outputs two arrays)
	$user_db =               $work_dir . '/configuration/users.php';
	
    //  Session file storage
	$session_storage = $work_dir . '/sessions';



// ===============================================================================
// SECURITY AND USER MANAGEMENT
// ===============================================================================

	// 2FA verification storage db
	$verify_store_file = $work_dir . '/data/2fa_verifications.json';
	
	// Only rely on modern crypto for passwords
	$force_argon2_only = true;
	
	// General security settings
	$login_failures = 5;
	$login_block_seconds = 600;
	$login_bruteforce_file =  $work_dir . '/data/login_failures.json';
	$brute_force_window = 6 * 3600; // 6 Hours (Window to remember previous lockout)
	$brute_force_factor = 3;        // Multiplier for each repeated lockout
	
	// Stateful tokens db 
	$login_stateful_tokens = $work_dir . '/data/stateful_tokens.json';

	// Global login rate limiting
	$global_login_rate_file = $work_dir . '/data/global_login_rate.json';
	$global_login_max_hits  = 20;   // attempts
	$global_login_window    = 60;   // seconds

	// Rate limit storage db
	$security_max_requests_file = $work_dir . '/data/security_maxrequests.json';
	
	// Proxies you are running and trusting. Default: Empty
	// Example: The static IPv4 address of an external Nginx/HAProxy VPS, or another external load balancer node:
	// '203.0.113.50',
 	$trusted_proxies = [
   ];
		
// ===============================================================================
// COOKIE AND SESSION MANAGEMENT
// ===============================================================================

	// Define the session inactivity limit
	$timeout_in_minutes = 60; 
	
	//  Cookie settings
	$cookie_name           = '2fa_verified';
	$cookie_valid_duration = 60 * 60 * 24 * 7 ; // 1 week
	$cookie_secret = 'SomeSecretKey(Change.this.to.something.secure!)';
	$cookie_is_ip_bound = false;


	// The domain names (eg. 'example.com') that are allowed to execude this code
	$allowed_domain = [
    ];
	
	// From its background, this is a part of a larger app for which these restrictions are necessary
	// You can leave these settings as is
	// 1. The domains that are allowed to enter only the cloud
	$cloud_only_domains = [
	];

	// 2. The paths that are allowed to start the cloud
	$cloud_only_paths = [
		'/cloud',
	];

// ===============================================================================
// GEOIP MODULE (OPTIONAL)
// ===============================================================================
	// Is GeoIP2 configured?
	//    Path for the databases: ./geoip
	//    Make sure to regularly update the database files on that dir, too. 
	// Maybe using a weekly cronjob.
	$enableGeoIP2 = false;
	
	// Array for the fields returned by the geoip module
	$geoip_data = array(
		'country_code' => "",
		'city' => "",
		'region' => "",
		'organization' => "",
		'admin_allowed' => True,
	);


	// Geoip whitelist
	$whitelist_admin_countries = array(
		"AT",
		"DE",
		"US",
	);


// ===============================================================================
// CLOUD MODULE
// ===============================================================================


	// Main app logo 
	$myDocpileLogo = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="100%" height="100%">
			<defs>
				<!-- Metallic gold gradient -->
				<linearGradient id="gold-grad" x1="0%" y1="0%" x2="100%" y2="100%">
				<stop offset="0%" stop-color="#D4AF37" />
				<stop offset="35%" stop-color="#AA7C11" />
				<stop offset="50%" stop-color="#FCEBAF" />
				<stop offset="65%" stop-color="#AA7C11" />
				<stop offset="100%" stop-color="#705000" />
				</linearGradient>
				
				<!-- Drop shadow for depth -->
				<filter id="shadow" x="-20%" y="-20%" width="140%" height="140%">
				<feDropShadow dx="0" dy="8" stdDeviation="6" flood-color="#000000" flood-opacity="0.3" />
				</filter>
			</defs>
			
			<!-- Global styling: stroke-width reduced to 8 -->
			<g stroke="url(#gold-grad)" stroke-width="8" stroke-linejoin="round" stroke-linecap="round" fill="none" filter="url(#shadow)" transform="translate(-45, -45) scale(1.176)">
				
				<!-- LEFT: Envelope Graphic -->
				<g>
				<rect x="44" y="145" width="210" height="145" rx="16" />
				<path d="M 60 145 L 149 225 L 238 145" />
				<path d="M 44 274 L 115 210" />
				<path d="M 254 274 L 183 210" />
				</g>
			
				<!-- RIGHT: Screen / Card with Keyhole Graphic -->
				<g>
				<rect x="275" y="145" width="193" height="145" rx="16" />
				<path d="M 360 195 A 16 16 0 1 1 384 195 L 392 250 L 352 250 Z" />
				</g>
			
				<!-- CENTER FRONT: Cloud Graphic (Flat bottom baseline) -->
				<!-- fill blocks out the lines behind it -->
				<path d="M 140 375 
						L 380 375 
						A 45 45 0 0 0 380 285 
						A 55 55 0 0 0 290 235 
						A 75 75 0 0 0 170 250 
						A 50 50 0 0 0 140 375 Z" 
					fill="#FFFFFF" />
			</g>
			</svg>';
			
	// Preview: Warn before preview threshold size 
	$cloud_max_preview_size = 5242880;
	
	// Preview: Automatically download on enter instead of preview, system level switch
	$cloud_autodownload = false;
	
	// Sharing: The full URL under which the shared dirs or files will be reachable from the internet
	$cloud_share_url = "https://example.com/cloud/index.php";
	
	// Sharing: The path and file name of the sharing database json
	$cloud_share_db = $work_dir . '/data/cloud_shares.json';
	
	// General: Path for the user profiles 
	$cloud_user_profiles = $work_dir . '/data/user_profiles';
	
	// General: Logfile path and name for all modifying tasks (copy, move, delete, upload...)
	// For data protection and security reasons, only switch on while debugging an error
	// $cloud_logfile = $work_dir . '/lists/cloud_requests.log';
	$cloud_logfile = '';
	
	// Public shares: Blocklist for $cloud_public_max_login_attempts
	$cloud_public_blocklist = $work_dir . '/data/cloud_blocklist.json';
	
	// Public shares: Maximum file size for uploads (you might consider changing this)
	// -> CHANGE THIS TO SUIT YOUR NEEDS!
	$cloud_public_quotas = '4GB';
	
	// Public shares: Download shared content as a ZIP - maximum uncompressed size
	$cloud_public_max_zip_size = 300 * 1024 * 1024; 
	
	// Public shares: Maximum login attempts before lockout 
	$cloud_public_max_login_attempts = 5;
	
	// Icons: Icon cache dir
	// -> CHANGE THIS IF NEEDED
	$cloud_icon_cache = '/home/mycloud/icon_cache';
	
	// Icons: Size in pixel 
	$cloud_icon_maxpixel = 90;
	
	// Icons: Quality used 
	$cloud_icon_quality = 60;
	
	// Preview: Picture cache dir
	// -> CHANGE THIS IF NEEDED
	$cloud_preview_cache = '/home/mycloud/preview_cache';
	
	// Preview: Size in pixel 
	$cloud_preview_maxpixel = 800;
	
	// Preview: Quality used
	$cloud_preview_quality = 66;
	
	// Upload: Security filter to not being able to upload dangerous files
	$cloud_upload_blocked_exts = ['php', 'php3', 'php4', 'php5', 'phtml', 'exe', 'sh', 'bat', 'cmd', 'htaccess'];
	
	// Recycler: How long should items be stored in the recycle bin?
	$cloud_recycle_bin_retention_days = 7;
	
	// Download: When to warn before creating a large ZIP file
	$zip_warn_limit = 300 * 1024 * 1024;
	
	// Admin Mode (SFTP): Main switch. If set to "false", admin_mode (SFTP) is not possible
	$cloud_enable_admin_mode = true;
	
    // Admin Mode (SFTP): Optional file to store the passwords for the SFTP accounts
    //                    Syntax: sha-256_of_the_cloud_key=password 
    //                    As the password is to be stored on the server together with the key,
	//                    this is almost as being in clear text. DO NOT USE ON PUBLIC SERVERS!
    //                    You have to create the file by hand, and edit it by hand
    //                    If the file does not exist, you are presented with a password login box
	$cloud_admin_mode_cloudlist = '';
	
	// OnlyOffice: Shared JWT secret - has to be the same as in the OnlyOffice docker image
	$cloud_onlyoffice_Secret = "MySecretKey123 (CHANGE THIS!!!)";
	
	// OnlyOffice: The network URL under which it is reachable
	//             At least the $cloud_onlyoffice_ext_URL has to be public since the clients have to connect there
	//             Leave these variables empty to disable OnlyOffice completely
	//	$cloud_onlyoffice_URL = "https://office.example.com";
	//	$cloud_onlyoffice_ext_URL = "https://office.example.com";
	$cloud_onlyoffice_URL = "";
	$cloud_onlyoffice_ext_URL = "";

	// Security & Content Scanning 
	$cloud_clamav_enabled     = false;        // Set to true to scan all incoming files
	$cloud_clamav_path        = 'clamdscan';  // clamdscan is recommended for daemon performance (or 'clamscan')

	// API Rate Limiting & Resource Quotas
	$cloud_rate_limit_enabled = true;         // Set to true to prevent API abuse
	$cloud_rate_limit_max     = 200;          // Maximum number of API requests allowed
	$cloud_rate_limit_window  = 30;           // Time window in seconds (e.g., 120 requests per 60 seconds)
	
	$cloud_ribbon_threshold = 11;             // Number of toolbar buttons that are displayed unstacked (without ribbons)
	
	$cloud_mail_only_localhost = true;


// ###############################################################################


// ===============================================================================
// SYSTEM GENERAL
// ===============================================================================


	date_default_timezone_set('Europe/Berlin');
	$language = 'en';
	if (isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
		$language = strtolower(substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2));
	}

